#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT,DIR_MD,DIR_UT, DIR_LB, DIR_RB, DIR_END };

enum OBJ_ID { OBJ_PLAYER, OBJ_MONSTER, OBJ_PBULLET, OBJ_MBULLET, OBJ_ITEM,OBJ_PET,OBJ_SHIELD,OBJ_MOUSE, OBJ_END };